var annotated_dup =
[
    [ "AddonApi", "classAddonApi.html", "classAddonApi" ],
    [ "AppearanceOptions", "classAppearanceOptions.html", "classAppearanceOptions" ],
    [ "BehaviorOptions", "classBehaviorOptions.html", "classBehaviorOptions" ],
    [ "BuiltInPacks", "classBuiltInPacks.html", "classBuiltInPacks" ],
    [ "ConfigParser", "classConfigParser.html", "classConfigParser" ],
    [ "ExerciseSummary", "classExerciseSummary.html", "classExerciseSummary" ],
    [ "ExportDialog", "classExportDialog.html", "classExportDialog" ],
    [ "FileUtils", "classFileUtils.html", "classFileUtils" ],
    [ "HistoryParser", "classHistoryParser.html", "classHistoryParser" ],
    [ "IAddon", "classIAddon.html", null ],
    [ "InitialSetup", "classInitialSetup.html", "classInitialSetup" ],
    [ "InputLabelWidget", "classInputLabelWidget.html", "classInputLabelWidget" ],
    [ "KeyboardOptions", "classKeyboardOptions.html", "classKeyboardOptions" ],
    [ "KeyboardUtils", "classKeyboardUtils.html", "classKeyboardUtils" ],
    [ "KeyboardWidget", "classKeyboardWidget.html", "classKeyboardWidget" ],
    [ "LanguageList", "classLanguageList.html", "classLanguageList" ],
    [ "LanguageManager", "classLanguageManager.html", "classLanguageManager" ],
    [ "LoadExerciseDialog", "classLoadExerciseDialog.html", "classLoadExerciseDialog" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "OptionsWindow", "classOptionsWindow.html", "classOptionsWindow" ],
    [ "PackEditor", "classPackEditor.html", "classPackEditor" ],
    [ "PackSelector", "classPackSelector.html", "classPackSelector" ],
    [ "Settings", "classSettings.html", "classSettings" ],
    [ "StatsDialog", "classStatsDialog.html", "classStatsDialog" ],
    [ "StringUtils", "classStringUtils.html", "classStringUtils" ],
    [ "TextView", "classTextView.html", "classTextView" ],
    [ "ThemeEngine", "classThemeEngine.html", "classThemeEngine" ],
    [ "TimeDialog", "classTimeDialog.html", "classTimeDialog" ],
    [ "Updater", "classUpdater.html", "classUpdater" ],
    [ "UpdaterQuestion", "classUpdaterQuestion.html", "classUpdaterQuestion" ]
];